ingresses:
  - "https://utenlandsadresser-tilbakekreving.intern.dev.nav.no"

env:
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

accessPolicy:
  outbound:
    external:
      - host: innkrevingsoppdrag.innkreving.skatteetaten-test.no # Skatteetaten
      - host: utenlandsadresser-unleash-api.nav.cloud.nais.io # Unleash

unleash:
  environment: development

replicas:
  min: 1
  max: 1
  scalingStrategy:
    cpu:
      thresholdPercentage: 100

resources:
  requests:
    cpu: 11m
    memory: 224Mi

azure:
  application:
    claims:
      groups:
        - "d5da316e-e4b8-4906-aa84-7fa87a1355f3" # 0000-CA-Tilbakekreving_Les_krav
        - "e7d9c694-d1f8-4dc9-90c4-106da1844552" # 0000-GA-ENHET_0106 - Nav Fredrikstad
        - "add39d0c-f8fb-4c8d-83e4-4450ba61afb0" # 0000-GA-ENHET_4411 - Nav Karmøy
