ingresses:
  - "https://utenlandsadresser-tilbakekreving.intern.dev.nav.no"

env:
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

accessPolicy:
  outbound:
    external:
      - host: api-test.sits.no # Skatteetaten

replicas:
  min: 1
  max: 2
  scalingStrategy:
    cpu:
      thresholdPercentage: 100

resources:
  requests:
    cpu: 5m
    memory: 440Mi

azure:
  application:
    claims:
      groups:
        - "30f17df5-c36c-4ad7-b862-48f56c95ebb2" # 0000-GA-FIA-Lesetilgang
        - "e7d9c694-d1f8-4dc9-90c4-106da1844552" # 0000-GA-ENHET_0106 - Nav Fredrikstad
        - "add39d0c-f8fb-4c8d-83e4-4450ba61afb0" # 0000-GA-ENHET_4411 - Nav Karmøy
