ingresses:
  - "https://tilbakekreving.intern.nav.no"

env:
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

maskinporten:
	scopes:
  	consumes:
			- name: "skatteetaten:innkrevingsoppdrag"

accessPolicy:
	outbound:
		external:
			- host: api.skatteetaten.no # Skatteetaten

replicas:
  min: 1
  max: 2
  scalingStrategy:
    cpu:
      thresholdPercentage: 100

resources:
  requests:
    cpu: 5m
    memory: 440Mi
