ingresses:
  - "https://utenlandsadresser-tilbakekreving.intern.nav.no"

env:
  JDK_JAVA_OPTIONS: "-XX:+UseParallelGC -XX:ActiveProcessorCount=4"

accessPolicy:
  outbound:
    external:
      - host: api.skatteetaten.no # Skatteetaten

replicas:
  min: 2
  max: 4
  scalingStrategy:
    cpu:
      thresholdPercentage: 100

resources:
  requests:
    cpu: 5m
    memory: 440Mi

azure:
  application:
    claims:
      groups:
        - "9d969830-2d8c-4c72-bb59-a067d8c4d883" # 0000-CA-Tilbakekreving_Les_krav
