apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "tilbakekreving"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2025-03-26T15:48:06.559796741"
spec:
  groups:
    - name: "tilbakekreving-alerts"
      rules:
        - alert: "problemer med deployment av tilbakekreving"
          expr: >
            kube_deployment_status_replicas_unavailable{deployment="tilbakekreving"} > 0
          for: "5m"
          labels:
            "namespace": "utenlandsadresser"
            "severity": "warning"
          annotations:
            "consequence": "tilbakekreving har problemer med å deploye"
            "action": "Fiks den!"
        - alert: "Feil i loggene"
          expr: >
            sum(increase(logback_events_total{app="tilbakekreving", level="error"}[3m])) > 0
          labels:
            namespace: "utenlandsadresser"
            severity: "critical"
            send_resolved: false
          annotations:
            "consequence": "tilbakekreving gjør ikke det den skal"
            "action": "Sjekk loggene og fiks eventuelle feil."
