apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "tilbakekreving"
  namespace: "utenlandsadresser"
  labels:
    "team": "utenlandsadresser"
  annotations:
    "start.nais.io/created-by": "Odd Gunnar Fatland"
    "start.nais.io/creationTimestamp": "2025-03-26T15:48:06.559796741"
    texas.nais.io/enabled: "true"
spec:
  observability:
    autoInstrumentation:
      enabled: false
      runtime: java
    logging:
      destinations:
        - id: "elastic"
  ingresses:
    {{#each ingresses}}
    - {{this}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: brukerflate-innkreving
    outbound:
      external:
        {{#each accessPolicy.outbound.external}}
        - host: {{this.host}}
        {{/each}}
  image: {{ image }}
  maskinporten:
    enabled: true
    scopes:
      consumes:
        - name: "skatteetaten:innkrevingsoppdrag"
  env:
    {{#each env}}
    - name: {{@key}}
      value: {{this}}
    {{/each}}
  liveness:
    failureThreshold: 3
    initialDelay: 10
    path: "/internal/isAlive"
    periodSeconds: 10
    timeout: 1
  readiness:
    failureThreshold: 3
    initialDelay: 10
    path: "/internal/isReady"
    periodSeconds: 10
    timeout: 1
  replicas:
    min: {{replicas.min}}
    max: {{replicas.max}}
    scalingStrategy:
      cpu:
        thresholdPercentage: {{replicas.scalingStrategy.cpu.thresholdPercentage}}
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
