skatteetaten {
  baseUrl: "https://innkrevingsoppdrag.innkreving.skatteetaten-test.no"
}

// 0000-CA-Tilbakekreving_Les_krav
kravTilgangsgruppe = "d5da316e-e4b8-4906-aa84-7fa87a1355f3"

entraProxy {
  apiTarget: "api://dev-gcp.sikkerhetstjenesten.entra-proxy/.default"
}
