nais {
  naisTokenEndpoint: "http://localhost:8080/token",
  naisTokenIntrospectionEndpoint: "http://localhost:8080/introspection",
  naisTokenExchangeEndpoint: "http://localhost:8080/exchange",
}

unleash {
  serverApiUrl: "",
  serverApiToken: "",
}

skatteetaten {
  baseUrl: "https://innkrevingsoppdrag.innkreving.skatteetaten-test.no"
}
