include classpath("kravtype.conf")

kravtypeAcl {
  // Nav tiltak Innlandet
  0587: [],
  // Nav økonomi stønad
  4151: [],
  // Klageinstans Tromsø
  4295: [],
  // Nav arbeid og ytelser Kristiania
  4403: [],
  // Nav arbeid og ytelser sykepenger
  4448: [],
  // Nav arbeid og ytelser dagpenger og lønnsgaranti
  4449: [],
  // Nav arbeid og ytelser dagpenger og lønnsgaranti
  4449: [],
  // Nav arbeid og ytelser grunn- og hjelpestønad
  4461: [],
  // Nav arbeid og ytelser egne ansatte
  4483: [],
  // Nav arbeid og ytelser - hjelpemidler
  4485: [],
  // Nav arbeid og ytelser - sykdom i familien
  4487: [],
  // Nav arbeid og ytelser - sykepenger
  4488: [],
  // Nav registerforvaltning
  4534: [],
  // Nav hjelpemiddelsentral Øst-Viken
  4701: [],
  // Nav hjelpemiddelsentral Oslo
  4703: [],
  // Nav hjelpemiddelsentral Innlandet-Elverum
  4704: [],
  // Nav hjelpemiddelsentral Innlandet-Gjøvik
  4705: [],
  // Nav hjelpemiddelsentral Vest-Viken
  4706: [],
  // Nav hjelpemiddelsentral Vestfold og Telemark
  4707: [],
  // Nav hjelpemiddelsentral Agder
  4710: [],
  // Nav hjelpemiddelsentral Rogaland
  4711: [],
  // Nav hjelpemiddelsentral Vestland-Bergen
  4712: [],
  // Nav hjelpemiddelsentral Møre og Romsdal
  4715: [],
  // Nav hjelpemiddelsentral Nordland
  4718: [],
  // Nav familie- og pensjonsytelser Oslo 2
  4803: [],
  // Nav familie- og pensjonsytelser Drammen
  4806: [],
  // Nav familie- og pensjonsytelser Bergen
  4812: [],
  // Nav familie- og pensjonsytelser Ålesund
  4815: [],
  // Nav familie- og pensjonsytelser Vadsø
  4820: [],
  // Nav familie- og pensjonsytelser Oslo 1
  4833: [],
  // Nav familie- og pensjonsytelser Stord
  4842: [],
  // Nav familie- og pensjonsytelser Tromsø
  4849: [],
  // Nav familie- og pensjonsytelser foreldrepenger
  4867: [],
  // Nav familie- og pensjonsytelser egne ansatte
  4883: [],
  // Klageinstans Bergen
  4294: [],
}